import { Award, BriefcaseBusiness, FolderKanban, Sparkles } from "lucide-react";
import { AdminDataError, DashboardCard, PageHeader } from "@/components/admin/admin-ui";
import { getAdminCounts } from "@/lib/portfolio/repository";

export default async function AdminDashboardPage() {
  let counts;
  try { counts = await getAdminCounts(); } catch { counts = null; }
  return <div className="mx-auto max-w-6xl"><PageHeader title="Content overview" description="Keep every public section current from one focused workspace." />{counts ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><DashboardCard href="/admin/experiences" label="Experience entries" value={counts.experiences} accent="#335cff" icon={<BriefcaseBusiness aria-hidden="true" className="size-5" />} /><DashboardCard href="/admin/projects" label="Projects" value={counts.projects} accent="#0f9f75" icon={<FolderKanban aria-hidden="true" className="size-5" />} /><DashboardCard href="/admin/certifications" label="Certifications" value={counts.certifications} accent="#e38b2c" icon={<Award aria-hidden="true" className="size-5" />} /><DashboardCard href="/admin/skills" label="Skills" value={counts.skills} accent="#9b59d0" icon={<Sparkles aria-hidden="true" className="size-5" />} /></div> : <AdminDataError />}<section className="mt-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_10px_35px_rgba(15,23,42,0.05)] sm:p-7"><h2 className="text-lg font-bold">Publishing workflow</h2><ol className="mt-5 grid gap-4 text-sm text-slate-600 md:grid-cols-3"><li className="rounded-xl bg-slate-50 p-4"><strong className="block text-slate-950">1. Create or edit</strong><span className="mt-1 block leading-6">Add clear content and upload media directly to Cloudinary.</span></li><li className="rounded-xl bg-slate-50 p-4"><strong className="block text-slate-950">2. Preview safely</strong><span className="mt-1 block leading-6">Keep unfinished entries as drafts until they are ready.</span></li><li className="rounded-xl bg-slate-50 p-4"><strong className="block text-slate-950">3. Publish</strong><span className="mt-1 block leading-6">Published updates appear on the portfolio after saving.</span></li></ol></section></div>;
}
